@echo off
if exist "Win32" rd /s /q "Win32" && echo Cleaning Win32...
if exist "x64"   rd /s /q "x64"   && echo Cleaning Debug...
if exist "ipch"  rd /s /q "ipch"  && echo Cleaning x64...
for /r %%i in (*.aps) do del /q "%%i" && echo Cleaning %%i...
for /r %%i in (*.ncb) do del /q "%%i" && echo Cleaning %%i...
for /r %%i in (*.sdf) do del /q "%%i" && echo Cleaning %%i...
for /r %%i in (*.vc.db) do del /q "%%i" && echo Cleaning %%i...